name: Tests

on:
  push:
    branches: master
  pull_request:

defaults:
  run:
    shell: bash
jobs:
  test:
    name: "Analyze and test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - run: flutter pub get
      - run: dart format --output=none --set-exit-if-changed .
      - run: dart analyze --fatal-infos --fatal-warnings
      - run: flutter test -r expanded
#      - uses: actions/setup-java@v1
#        with:
#          java-version: '12.x'

